import { statisticsAppearanceCopy } from '@/components/statistics/appearance-copy';
import type { Language } from '@/lib/i18n/config';

const en = {
  ...statisticsAppearanceCopy.en,
  actions: 'Statistic actions',
  focusView: 'Focus view',
  addFirst: 'Add your first statistic',
  addStatistic: 'Add statistic',
  allStatuses: 'All statuses',
  backToBoard: 'Back to board',
  bucket: 'Time bucket',
  bucketDay: 'Day',
  bucketMonth: 'Month',
  bucketQuarter: 'Quarter',
  bucketWeek: 'Week',
  bucketYear: 'Year',
  cancel: 'Cancel',
  create: 'Add to canvas',
  createTitle: 'Create statistic',
  dateCompleted: 'Completion date',
  dateCreated: 'Creation date',
  dateDeadline: 'Deadline',
  dateField: 'Date field',
  dateProperty: 'Date property',
  dateUpdated: 'Last update',
  delete: 'Delete',
  deleteConfirm: 'Delete statistic',
  deleteDescription:
    'This removes “{name}” from the canvas. Task data is not affected.',
  edit: 'Edit',
  editTitle: 'Edit statistic',
  emptyDescription:
    'Build a view of your workflow with a KPI, breakdown, or timeline.',
  emptyTitle: 'Your statistics canvas is empty',
  filteredShare: '{percentage}% of filtered tasks',
  groupBy: 'Group by',
  groupDate: 'Date',
  groupProperty: 'Custom property',
  groupStatus: 'Status',
  heading: 'Statistics',
  measure: 'Measure',
  measureAverage: 'Average',
  measureCompletionRate: 'Completion rate',
  measureCount: 'Task count',
  measureMaximum: 'Maximum',
  measureMinimum: 'Minimum',
  measureOnTime: 'On-time rate',
  measureOverdue: 'Overdue tasks',
  measureResolution: 'Average resolution time',
  measureSum: 'Sum',
  moveEarlier: 'Move {name} earlier',
  moveLater: 'Move {name} later',
  multiValueNote: 'A task can contribute to more than one category.',
  name: 'Name',
  namePlaceholder: 'e.g. Monthly completions',
  noChartData: 'No matching data for this dimension yet.',
  notAvailable: 'Not available',
  numericProperty: 'Number property',
  other: 'Other',
  property: 'Property',
  requiredDateProperty: 'Choose a date property.',
  requiredName: 'Enter a name for this statistic.',
  requiredProperty: 'Choose a compatible property.',
  sample: '{count} tasks in the sample',
  save: 'Save changes',
  saveFailed: 'The statistic could not be saved.',
  scope: 'Task scope',
  scopeActive: 'Active tasks',
  scopeAll: 'All tasks',
  scopeCompleted: 'Completed tasks',
  skipToStatistics: 'Skip to statistics',
  statusFilter: 'Statuses',
  statusFilterDescription: 'Leave empty to include every status.',
  subtitle: 'A clear view of your work, from progress to patterns.',
  tasks: 'tasks',
  unassigned: 'Unassigned',
  visualization: 'Visualization',
  visualizationBar: 'Bar chart',
  visualizationDonut: 'Donut chart',
  visualizationKpi: 'KPI',
  visualizationLine: 'Timeline',
  widgetsConfigured: '{count} configured statistics',
} as const;

type StatisticsCopyKey = keyof typeof en;

const es: Record<StatisticsCopyKey, string> = {
  ...statisticsAppearanceCopy.es,
  actions: 'Acciones de la estadística',
  focusView: 'Vista de enfoque',
  addFirst: 'Añade tu primera estadística',
  addStatistic: 'Añadir estadística',
  allStatuses: 'Todos los estados',
  backToBoard: 'Volver al tablero',
  bucket: 'Intervalo temporal',
  bucketDay: 'Día',
  bucketMonth: 'Mes',
  bucketQuarter: 'Trimestre',
  bucketWeek: 'Semana',
  bucketYear: 'Año',
  cancel: 'Cancelar',
  create: 'Añadir al panel',
  createTitle: 'Crear estadística',
  dateCompleted: 'Fecha de finalización',
  dateCreated: 'Fecha de creación',
  dateDeadline: 'Deadline',
  dateField: 'Campo de fecha',
  dateProperty: 'Propiedad de fecha',
  dateUpdated: 'Última actualización',
  delete: 'Eliminar',
  deleteConfirm: 'Eliminar estadística',
  deleteDescription: 'Esto quita “{name}” del panel. No afecta a las tareas.',
  edit: 'Editar',
  editTitle: 'Editar estadística',
  emptyDescription:
    'Crea una vista de tu flujo con un KPI, desglose o cronología.',
  emptyTitle: 'Tu panel de estadísticas está vacío',
  filteredShare: '{percentage}% de las tareas filtradas',
  groupBy: 'Agrupar por',
  groupDate: 'Fecha',
  groupProperty: 'Propiedad personalizada',
  groupStatus: 'Estado',
  heading: 'Estadísticas',
  measure: 'Medida',
  measureAverage: 'Media',
  measureCompletionRate: 'Tasa de finalización',
  measureCount: 'Número de tareas',
  measureMaximum: 'Máximo',
  measureMinimum: 'Mínimo',
  measureOnTime: 'Tasa de puntualidad',
  measureOverdue: 'Tareas vencidas',
  measureResolution: 'Tiempo medio de resolución',
  measureSum: 'Suma',
  moveEarlier: 'Mover {name} antes',
  moveLater: 'Mover {name} después',
  multiValueNote: 'Una tarea puede contribuir a más de una categoría.',
  name: 'Nombre',
  namePlaceholder: 'p. ej., Finalizaciones mensuales',
  noChartData: 'Todavía no hay datos para esta dimensión.',
  notAvailable: 'No disponible',
  numericProperty: 'Propiedad numérica',
  other: 'Otros',
  property: 'Propiedad',
  requiredDateProperty: 'Elige una propiedad de fecha.',
  requiredName: 'Escribe un nombre para esta estadística.',
  requiredProperty: 'Elige una propiedad compatible.',
  sample: '{count} tareas en la muestra',
  save: 'Guardar cambios',
  saveFailed: 'No se ha podido guardar la estadística.',
  scope: 'Alcance de tareas',
  scopeActive: 'Tareas activas',
  scopeAll: 'Todas las tareas',
  scopeCompleted: 'Tareas terminadas',
  skipToStatistics: 'Saltar a las estadísticas',
  statusFilter: 'Estados',
  statusFilterDescription: 'Déjalo vacío para incluir todos los estados.',
  subtitle: 'Una vista clara de tu trabajo, del progreso a los patrones.',
  tasks: 'tareas',
  unassigned: 'Sin asignar',
  visualization: 'Visualización',
  visualizationBar: 'Gráfico de barras',
  visualizationDonut: 'Gráfico de anillo',
  visualizationKpi: 'KPI',
  visualizationLine: 'Cronología',
  widgetsConfigured: '{count} estadísticas configuradas',
};

const catalogs = { en, es } as const;

/** Formats a statistics message in the active application language. */
export function getStatisticsCopy(
  language: Language,
  key: StatisticsCopyKey,
  values: Readonly<Record<string, string | number>> = {},
): string {
  return catalogs[language][key].replace(
    /\{([A-Za-z][A-Za-z0-9_]*)\}/g,
    (placeholder, name: string) =>
      Object.prototype.hasOwnProperty.call(values, name)
        ? String(values[name])
        : placeholder,
  );
}

export type { StatisticsCopyKey };
